import type { Metadata } from "next";
import { Barlow, Inter, JetBrains_Mono, Poppins } from "next/font/google";
import "./globals.scss";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });
const barlow = Barlow({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  display: "swap",
  preload: true,
  variable: "--font-barlow",
});
const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  display: "swap",
  preload: true,
  variable: "--font-poppins",
});
const jetbrains_mono = JetBrains_Mono({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  subsets: ["cyrillic", "latin", "latin-ext", "vietnamese"],
  display: "swap",
  preload: true,
  adjustFontFallback: true,
  style: "normal",
  variable: "--font-jetbrains-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.className,
          barlow.variable,
          poppins.variable,
          jetbrains_mono.variable,
          "dark antialiased"
        )}
      >
        {children}
      </body>
    </html>
  );
}
